services:
  auth:
    image: alexsryzhkov2003/cars-service
    container_name: auth
    restart: always
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: pract8
      DB_PORT: 5432
      SERVER_HOST: "0.0.0.0"
    ports:
      - "3000:3000"
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pract8
    ports:
      - "5432:5432"