services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pract8
    ports:
      - "5432:5432"